version = 0.1

[default.deploy.parameters]
stack_name = "Proyecto-Escalables"
resolve_s3 = true
s3_prefix = "Proyecto-Escalables"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-2"
